name: Maven Build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Java JDK
      uses: actions/setup-java@v2.5.0
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Build using maven
      run: mvn clean verify
