name: Maven Build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  workflow_dispatch:
    inputs:
      releaseBuild:
        description: 'Release build'     
        required: true
        default: 'false'
        type: boolean

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Java JDK
      uses: actions/setup-java@v2.5.0
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Build using maven and nightly versions
      if: ${{ !github.event.inputs.releaseBuild }}
      run: mvn clean verify
    - name: Build using maven and release versions
      if: ${{ github.event.inputs.releaseBuild }}
      run: mvn clean verify -Drelease
