name: Maven Build

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build using maven docker image
      run: docker run --rm -v ${{ github.workspace }}:/tmp/ws -w /tmp/ws maven:3.8.4-openjdk-11 mvn clean verify
